name: prebuild
on: [push]

jobs:
  package:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true

      - name: Use nodejs
        uses: actions/setup-node@v1
        with:
          node-version: 14.8.0

      - name: install Linux dependencies
        run: |
          sudo add-apt-repository ppa:jonathonf/ffmpeg-4
          sudo apt-get update
          sudo apt-get install libavcodec-dev libavformat-dev libavdevice-dev libavfilter-dev libavutil-dev libpostproc-dev libswresample-dev libswscale-dev
        if: ${{ runner.os == 'Linux' }}

      - name: install Mac dependencies
        run: brew install nasm pkg-config ffmpeg
        if: ${{ runner.os == 'macOS'}}

      - name: install Windows dependencies
        run: node ./install_ffmpeg.js
        if: ${{ runner.os == 'Windows'}}

      - run: npm install
      - run: npm run lint
      - name: prebuild for node (N-API)
        run: npx prebuild --runtime napi --upload ${{ secrets.GITHUB_TOKEN }}
      - name: prebuild for electron 10 (ABI 82)
        run: npx prebuild --runtime electron --target 82 --upload ${{ secrets.GITHUB_TOKEN }}
      - name: prebuild for electron 11 (ABI 85)
        run: npx prebuild --runtime electron --target 85 --upload ${{ secrets.GITHUB_TOKEN }}
