name: prebuild
on: [push]

jobs:
  package:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true

      - name: Use nodejs
        uses: actions/setup-node@v1
        with:
          node-version: 14.8.0

      - name: install Linux dependencies
        run: |
          sudo add-apt-repository ppa:jonathonf/ffmpeg-4
          sudo apt-get update
          sudo apt-get install libavcodec-dev libavformat-dev libavdevice-dev libavfilter-dev libavutil-dev libpostproc-dev libswresample-dev libswscale-dev
        if: ${{ runner.os == 'Linux' }}

      - run: node ./install_ffmpeg.js
      - run: npm install
      - run: npm run lint
      - run: npx prebuild --runtime napi --upload $GITHUB_TOKEN
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
